#!/usr/bin/env ruby

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require APP_PATH
Rails.application.require_environment!

regions = MetropolitanArea.all

puts "Writing #{ARGV[0].inspect} for year #{ARGV[1].inspect}..."
exporter = JsonExporter.new(ARGV[0])
exporter.export(regions)
