#!/usr/bin/env ruby

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require APP_PATH
Rails.application.require_environment!

logger = Logger.new(STDOUT)

puts "Reading #{ARGV[0].inspect} for year #{ARGV[1].inspect}..."
importer = ShpImporter.new(ARGV[0], ARGV[1].to_i, :logger => logger)
importer.import
