#!/usr/bin/env ruby

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require APP_PATH
Rails.application.require_environment!

puts "Reading #{ARGV[0].inspect}..."
importer = CsvImporter.new(ARGV[0], 'Subdivision')
importer.import
